version: '3'

services:
  mysql-db:
    build:
      context: mysql-db
      dockerfile: Dockerfile
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'stud'
      MYSQL_USER: 'stud'
      MYSQL_PASSWORD: 'stud'

  poco-rest-app:
    build:
      context: poco-rest-app
      dockerfile: Dockerfile
    container_name: poco-rest-app
    environment:
      MYSQL_HOST: 'mysql-db'
      MYSQL_DATABASE: 'stud'
      MYSQL_USER: 'stud'
      MYSQL_PASSWORD: 'stud'
    ports:
      - '8080:8080'