version: '3'

services:
  mysql-db:
    build:
      context: mysql-db
      dockerfile: Dockerfile
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'stud'
      MYSQL_USER: 'stud'
      MYSQL_PASSWORD: 'stud'

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: 'stud'
      RABBITMQ_DEFAULT_PASS: 'stud'
    ports:
      - '15672:15672'

  poco-rest-app:
    build:
      context: poco-rest-app
      dockerfile: Dockerfile
    container_name: poco-rest-app
    environment:
      MYSQL_HOST: 'mysql-db'
      MYSQL_DATABASE: 'stud'
      MYSQL_USER: 'stud'
      MYSQL_PASSWORD: 'stud'
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_PORT: '5672'
      RABBITMQ_USER: 'stud'
      RABBITMQ_PASSWORD: 'stud'
    depends_on:
      - mysql-db
      - rabbitmq
    ports:
      - '8080:8080'